services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: base-dev
    volumes:
      - .:/data/
    environment:
      - TZ=Europe/Paris
    env_file:
      - .env.local
    ports:
      - "8000:8000"
    networks:
      - default
  # db:
  #   image: postgres:17.1
  #   environment:
  #     - TZ=Europe/Paris
  #   env_file:
  #     - .env.local
  #   ports:
  #     - "5433:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   networks:
  #     default:
  #       aliases:
  #         - postgres-db
networks:
  default:
    driver: bridge
volumes:
  postgres_data: